event_recommender/urls.py
from django.contrib import admin
from django.urls import path,include

from events.views import getHomePage

urlpatterns = [
    path('events/',include('events.urls')),
    path('user/',include('user_app.urls')),
    path('collector/',include('collector.urls')),
    path('recommender/',include('recommender.urls')),
    path('organizer/',include('organizer.urls')),
    path('admin/', admin.site.urls),
    path('',getHomePage,name="home_page"),
]

events/urls.py
from django.urls import path

from . import views

from events.views import EventsListView,EventDetailView

urlpatterns = [
    # path('', views.index, name='index'),
    path('',EventsListView.as_view(),name='event_list'),
    path('<int:category_pk>',EventsListView.as_view(),name='event_list'),
    path('<slug:search_q>',EventsListView.as_view(),name='event_list'),
    path('<slug:pk>/',EventDetailView.as_view(),name='event_detail'),
    path('<slug:location>',EventsListView.as_view(),name='event_list')
]

organizer/urls.py
from . import views
from django.urls import path
from organizer import views  
urlpatterns = [     
    path('new', views.org,name='new-organizer'),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
]

organizer/models.py
from django.db import models
from events.models import Event_category_model
# Create your models here. 
class Organizer(models.Model):  
    ename = models.CharField(max_length=200)  
    edesc = models.CharField(max_length=1000)  
    eguest = models.CharField(max_length=150)  
    eloc = models.CharField(max_length=150)
    ecat = models.CharField(max_length=200)
    class Meta:  
        db_table = "organizer" 

organizer/forms.py
from django import forms  
from organizer.models import Organizer  
from events.models import Event_category_model
class OrgForm(forms.ModelForm):  
    class Meta:  
        model = Organizer  
        fields = "__all__"  

organizer/views.py
from django.shortcuts import render, redirect  
from organizer.forms import OrgForm  
from organizer.models import Organizer  
from events.models import Event_category_model
# Create your views here.  
def org(request):  
    if request.method == "POST":  
        form = OrgForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/organizer/show')  
            except:  
                pass  
    else:  
        form = OrgForm()  
    return render(request,'organizer/index.html',{'form':form})  
def show(request):  
    organizer = Organizer.objects.all()  
    return render(request,"organizer/show.html",{'organizer':organizer})  
def edit(request, id):  
    organizer = Organizer.objects.get(id=id)  
    return render(request,'organizer/edit.html', {'organizer':organizer})  
def update(request, id):  
    organizer = Organizer.objects.get(id=id)  
    form = OrgForm(request.POST, instance = organizer)  
    if form.is_valid():  
        form.save()  
        return redirect("/organizer/show")  
    return render(request, 'organizer/edit.html', {'organizer': organizer})  
def destroy(request, id):  
    organizer = Organizer.objects.get(id=id)  
    organizer.delete()  
    return redirect("/organizer/show")  

templates/organizer/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Edit Event Details</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</head>  
<body>  
<form method="POST" class="post-form" action="/organizer/update/{{organizer.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Event Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Event Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="20" value="{{ organizer.ename }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Event Descriptiom:</label>  
    <div class="col-sm-4">  
        <input type="text" name="edesc" id="id_edesc" required maxlength="100" value="{{ organizer.edesc }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Event Guest:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eguest" id="id_eguest" required maxlength="254" value="{{ organizer.eguest }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Event Location:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eloc" id="id_eloc" required maxlength="150" value="{{ organizer.eloc }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Event Category:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ecat" id="id_ecat" required maxlength="150" value="{{ organizer.ecat }}" />  
    </div>  
  </div> 
  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

templates/organizer/index.html

<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Organizer</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"> 
    <!-- <link rel="stylesheet" href="{% static 'styles/login.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}" /> -->
    
</head>  
<body>  
 
<section>
 
<form method="POST" class="post-form" action="/organizer/new">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <center><h3>Enter Event Details </h3></center>  
    <hr>
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">EVENT NAME:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">EVENT DESCRIPTION:</label>  
    <div class="col-sm-4">  
      {{ form.edesc }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">EVENT GUEST:</label>  
    <div class="col-sm-4">  
      {{ form.eguest }}  
    </div>  
  </div> 
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">EVENT LOCATION:</label>  
    <div class="col-sm-4">  
      {{ form.eloc }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">EVENT CATEGORY:</label>  
    <div class="col-sm-4">  
      
      {{ form.ecat }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
    <hr>
    <center><a href="/organizer/show" class="btn btn-primary">VIEW EVENTS</a></center> 
 
</form>  


</section>

</body>  
</html>  

templates/organizer/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Event Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>EVENT NAME</th>  
        <th>EVENT DESCRIPTION</th>  
        <th>EVENT GUEST</th>
        <th>EVENT LOCATION</th>  
        <th>EVENT CATEGORY</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for org in organizer %}  
    <tr>  
        <td>{{ org.ename }}</td>  
        <td>{{ org.edesc }}</td>  
        <td>{{ org.eguest }}</td>  
        <td>{{ org.eloc }}</td> 
        <td>{{ org.ecat }}</td> 
        <td>  
            <a href="/organizer/edit/{{ org.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/organizer/delete/{{ org.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/organizer/new" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html> 